import { chromium } from './auth.mjs';
import { execFileSync, execSync } from 'node:child_process';
import { OUT, B, CHROME, FIX } from './env.mjs';

let fails = 0;
const ok = (name, condition, detail = '') => { if (!condition) fails++; console.log(condition ? 'PASS' : 'FAIL', name, detail); };
const until = async (fn, ms = 20000) => { const started = Date.now(); while (Date.now() - started < ms) { if (await fn().catch(() => false)) return true; await new Promise((r) => setTimeout(r, 200)); } return false; };
const tool = async (name) => { await page.getByRole('button', { name: 'Editor tools' }).click(); await page.getByRole('menuitem', { name, exact: true }).click(); await page.locator('[data-dropdown-menu-content]').waitFor({ state: 'hidden' }); };
const edit = async (name) => { await page.getByRole('button', { name: 'Edit actions' }).click(); await page.getByRole('menuitem', { name, exact: true }).click(); await page.locator('[data-dropdown-menu-content]').waitFor({ state: 'hidden' }); };
const browser = await chromium.launch({ executablePath: CHROME, args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', `--use-file-for-fake-audio-capture=${OUT}/voice-noisy.wav`, '--autoplay-policy=no-user-gesture-required', '--disable-audio-output'] });
const ctx = await browser.newContext({ ignoreHTTPSErrors: true, permissions: ['microphone'], acceptDownloads: true, viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const errors = []; page.on('pageerror', (e) => errors.push(e.message));

await page.goto(B);
await page.goto(`${B}/episodes/142/studio`);
let startButton = page.locator('[data-studio-actions] button[type="submit"]');
ok('studio Start session keeps full height', Math.round((await startButton.boundingBox()).height) >= 48);
await page.setViewportSize({ width: 1280, height: 650 });
await page.locator('input[name="format"][value="guest"]').check({ force: true });
ok('Start session stays usable on a short guest setup screen', Math.round((await startButton.boundingBox()).height) >= 48 && await startButton.isVisible());
await page.screenshot({ path: `${OUT}/studio-short-screen.png`, fullPage: true });
await page.emulateMedia({ colorScheme: 'dark' });
await page.screenshot({ path: `${OUT}/studio-short-screen-dark.png`, fullPage: true });
await page.emulateMedia({ colorScheme: 'light' });
await page.setViewportSize({ width: 1440, height: 900 });
await page.goto(B);
// Seed a completed recording through the real API. Editor tests do not depend on
// microphone availability; recording-to-editor routing is covered by solo/guest flows.
await page.evaluate(async () => {
  const rate = 48000, seconds = 12, id = 'editor-browser-main';
  const pcm = new Int16Array(rate * seconds);
  for (let i = 0; i < pcm.length; i++) pcm[i] = Math.round(Math.sin(i * 2 * Math.PI * 220 / rate) * 4000 + Math.sin(i * 2 * Math.PI * 900 / rate) * 1800);
  const meta = { id, episodeId: '142', name: 'Session', kind: 'session', speaker: 'Host', number: 1, startLine: 0, startText: '', device: 'Browser fixture', sampleRate: rate, bitDepth: 16, channels: 1, samples: pcm.length, segments: 3, startedAt: Date.now(), updatedAt: Date.now(), status: 'done', peaks: [], markers: [{ kind: 'retake', t: 3, line: 0 }], lineLog: [{ t: 0, line: 0 }, { t: 3, line: 0 }, { t: 7, line: 1 }] };
  const put = async (url, body, json = true) => { const response = await fetch(url, { method: 'PUT', headers: json ? { 'Content-Type': 'application/json' } : {}, body: json ? JSON.stringify(body) : body }); if (!response.ok) throw new Error(`Fixture failed: ${response.status}`); };
  await put(`/api/takes/${id}`, { meta, done: false });
  for (let n = 0; n < 3; n++) await put(`/api/takes/${id}/segments/${n + 1}`, pcm.slice(n * rate * 4, (n + 1) * rate * 4).buffer, false);
  await put(`/api/takes/${id}`, { meta, done: true });
});
await page.goto(`${B}/episodes/142/editor?take=editor-browser-main`);
if (!await until(async () => await page.locator('[data-editor]').isVisible(), 15000)) throw new Error(`Editor did not mount: ${await page.locator('[data-loading]').textContent().catch(() => 'loading removed')} | ${errors.join(' | ')} | ${(await page.locator('body').textContent()).slice(-500)}`);
ok('completed session opens editor directly', page.url().includes('/editor?take='));
ok('timeline has a host track', (await page.locator('[data-track]').count()) >= 1);
ok('top and bottom controls are present', (await page.locator('[data-export-open]').count()) === 1 && (await page.locator('[data-editor-play]').count()) === 1);
ok('empty recording metadata generates a visible waveform', await until(async () => page.locator('[data-track]').first().locator('[data-waveform-peak]').evaluateAll((nodes) => nodes.some((node) => parseFloat(getComputedStyle(node).height) > 6))));
const playbackStarted = Date.now();
await page.locator('[data-editor-play]').click();
ok('short recording starts from a bounded first render', await until(async () => await page.locator('[data-editor-play]').getAttribute('aria-label') === 'Pause', 10000) && Date.now() - playbackStarted < 10000);
ok('host meter shows a live processed dBFS peak', await until(async () => Number.isFinite(Number(await page.locator('[data-track]').first().locator('[data-track-meter]').getAttribute('data-peak-dbfs'))) && Number(await page.locator('[data-track]').first().locator('[data-track-meter]').getAttribute('data-peak-dbfs')) > -60, 5000));
ok('master output has stacked left and right dBFS meters', await until(async () => {
  const left = await page.getByRole('meter', { name: 'Master left level' }).getAttribute('aria-valuetext');
  const right = await page.getByRole('meter', { name: 'Master right level' }).getAttribute('aria-valuetext');
  return left !== '−∞ dBFS' && right !== '−∞ dBFS';
}, 5000) && await page.locator('[data-master-meter]').isVisible());
ok('large playhead and duration flank the scrubber before master levels', await page.evaluate(() => {
  const current = document.querySelector('[data-current-time]');
  const scrubber = document.querySelector('input[aria-label="Playhead"]');
  const duration = document.querySelector('[data-duration-time]');
  const meter = document.querySelector('[data-master-meter]');
  return !!current && !!scrubber && !!duration && !!meter
    && current.getBoundingClientRect().right < scrubber.getBoundingClientRect().left
    && scrubber.getBoundingClientRect().right < duration.getBoundingClientRect().left
    && duration.getBoundingClientRect().right < meter.getBoundingClientRect().left
    && parseFloat(getComputedStyle(current).fontSize) >= 15;
}));
await page.screenshot({ path: `${OUT}/editor-meter-light.png`, fullPage: true });
ok('playback crosses the first render window', await until(async () => Number(await page.locator('input[aria-label="Playhead"]').inputValue()) > 5, 10000));
await page.getByRole('button', { name: 'Stop', exact: true }).click();
ok('meter resets when playback stops', await page.locator('[data-track]').first().locator('[data-track-meter]').getAttribute('data-peak-dbfs') === '-Infinity');
ok('master meters reset when playback stops', await page.getByRole('meter', { name: 'Master left level' }).getAttribute('aria-valuetext') === '−∞ dBFS' && await page.getByRole('meter', { name: 'Master right level' }).getAttribute('aria-valuetext') === '−∞ dBFS');
await page.screenshot({ path: `${OUT}/editor-desktop.png`, fullPage: true });
await page.emulateMedia({ colorScheme: 'dark' });
await page.locator('[data-editor-play]').click();
await until(async () => Number.isFinite(Number(await page.locator('[data-track]').first().locator('[data-track-meter]').getAttribute('data-peak-dbfs'))), 5000);
await page.screenshot({ path: `${OUT}/editor-meter-dark.png`, fullPage: true });
await page.getByRole('button', { name: 'Stop', exact: true }).click();
await page.emulateMedia({ colorScheme: 'light' });
await page.getByRole('button', { name: 'Editor tools' }).click();
if (await page.locator('[data-retakes-open]').textContent().then((x) => x.includes('('))) {
  await page.locator('[data-retakes-open]').click();
  ok('retake review shows attempts', (await page.locator('[data-retake]').count()) >= 1);
  await page.getByRole('button', { name: 'Keep last take' }).first().click();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Editor tools' }).click();
  ok('retake review clears the required count', !(await page.locator('[data-retakes-open]').textContent()).includes('('));
  await page.keyboard.press('Escape');
}
await page.locator('[data-track-fx]').first().click();
ok('FX opens in a sheet', await page.locator('#fx-title').isVisible());
await page.getByRole('button', { name: 'Advanced', exact: true }).click();
ok('advanced EQ has ten bands', await page.locator('input[aria-label^="EQ "]').count() === 10);
await page.getByLabel('EQ 1000 Hz', { exact: true }).fill('3');
await page.getByLabel('Attack', { exact: false }).fill('25');
await page.screenshot({ path: `${OUT}/editor-advanced.png`, fullPage: true });
await page.getByRole('button', { name: 'Simple', exact: true }).click();
ok('collapsing advanced retains custom settings', await page.getByText('Advanced EQ and compression are active.', { exact: false }).isVisible());
await page.getByRole('button', { name: 'Apply FX' }).click();
ok('server autosave confirms', await until(async () => (await page.locator('[data-save-state]').getAttribute('data-save-state')) === 'saved'));
await ctx.setOffline(true);
await page.locator('input[aria-label$=" level"]').first().evaluate((input) => { input.value = '-1'; input.dispatchEvent(new Event('input', { bubbles: true })); });
ok('offline edits wait for connection', await until(async () => (await page.locator('[data-save-state]').getAttribute('data-save-state')) === 'offline'));
await ctx.setOffline(false);
ok('autosave resumes online', await until(async () => (await page.locator('[data-save-state]').getAttribute('data-save-state')) === 'saved'));
let failedUpload = false; const uploadIds = [];
await page.route('**/api/media/*', async (route) => {
  if (route.request().method() !== 'PUT') return route.continue();
  uploadIds.push(new URL(route.request().url()).pathname);
  if (!failedUpload) { failedUpload = true; await new Promise((r) => setTimeout(r, 600)); return route.fulfill({ status: 502, body: 'Bad gateway' }); }
  return route.continue();
});
await page.locator('[data-editor-import]').setInputFiles(`${FIX}/sting.wav`);
ok('import reports progress immediately', await until(async () => await page.locator('[data-import-status]').isVisible(), 2000));
ok('import progress stays in the lower corner', await page.locator('[data-import-status]').evaluate((node) => getComputedStyle(node).position === 'fixed' && node.getBoundingClientRect().right > innerWidth - 32));
await page.getByRole('button', { name: 'Retry upload' }).waitFor();
ok('502 gives an actionable retry', await page.getByRole('alert').textContent().then((s) => s.includes('502') && s.includes('retained')));
await page.getByRole('button', { name: 'Retry upload' }).click();
ok('browser-decodable import becomes a track', await until(async () => (await page.locator('[data-track]').count()) === 2));
ok('imported audio gains a waveform', await until(async () => await page.locator('[data-track]').last().locator('[data-waveform-peak]').count() > 0));
ok('retry reuses the same upload id', uploadIds.length === 2 && uploadIds[0] === uploadIds[1]);
ok('English editor opts out of translation', await page.locator('html').getAttribute('lang') === 'en' && await page.locator('meta[name="google"]').getAttribute('content') === 'notranslate');
const clip = page.locator('[data-clip]').first();
await clip.click({ position: { x: 20, y: 35 } });
ok('clip details open without a timeline-wide number row', await page.locator('[data-clip-popover]').isVisible());
await page.getByLabel('Source out').fill('0:05.000'); await page.getByLabel('Source out').press('Tab');
ok('trim changes the source end', await page.getByLabel('Source out').inputValue() === '0:05.000');
await page.getByLabel('Source out').fill('0:06.000'); await page.getByLabel('Source out').press('Tab');
ok('trim restores source audio', await page.getByLabel('Source out').inputValue() === '0:06.000');
await page.getByLabel('Source out').fill('0:03.000'); await page.getByLabel('Source out').press('Escape');
await clip.click({ position: { x: 20, y: 35 } });
ok('Escape discards an uncommitted clip value', await page.getByLabel('Source out').inputValue() === '0:06.000');
await page.getByRole('button', { name: 'Close clip details' }).click();
await edit('Undo');
await edit('Undo');
ok('import remains after undoing trim changes', await page.locator('[data-track]').count() === 2);
ok('editor menus release waveform pointer events', await until(async () => page.locator('body').evaluate((body) => getComputedStyle(body).pointerEvents !== 'none'), 2000));
ok('Select and Move modes are absent', await page.getByRole('button', { name: /^(Select|Move)$/ }).count() === 0);
const box = await clip.boundingBox();
await page.mouse.move(box.x + 20, box.y + 35); await page.mouse.down(); await page.mouse.move(box.x + 60, box.y + 35, { steps: 5 }); await page.mouse.up();
ok('direct drag moves waveform', await until(async () => Number.parseFloat((await clip.getAttribute('style')).match(/left:\s*([\d.]+)px/)?.[1] ?? '0') > 8, 2000), await clip.getAttribute('style'));
ok('import survives direct drag', await page.locator('[data-track]').count() === 2);
await edit('Undo');
ok('import survives direct-drag undo', await page.locator('[data-track]').count() === 2);
const restored = await clip.boundingBox();
await page.mouse.move(restored.x + 20, restored.y + 35); await page.mouse.down(); await page.mouse.move(restored.x + 55, restored.y + 35, { steps: 5 }); await page.keyboard.press('Escape'); await page.mouse.up();
ok('Escape cancels a move', Number.parseFloat((await clip.getAttribute('style')).match(/left: ([\d.]+)px/)?.[1] ?? '0') === 0);
ok('import survives escape', await page.locator('[data-track]').count() === 2);
await page.keyboard.down('Shift');
await page.mouse.move(restored.x + 12, restored.y + 35); await page.mouse.down(); await page.mouse.move(restored.x + 32, restored.y + 35, { steps: 5 }); await page.mouse.up();
await page.keyboard.up('Shift');
ok('range has a visible start, end and duration', await page.locator('[data-selection-summary]').isVisible() && (await page.locator('[data-selection-summary]').textContent()).includes('→') && await page.locator('[data-time-selection]').count() >= 1);
const selectedSummary = await page.locator('[data-selection-summary]').textContent();
await clip.click({ button: 'right', position: { x: 20, y: 35 } });
ok('right-click inside a range preserves it', await page.locator('[data-editor-context-menu]').isVisible() && await page.locator('[data-selection-summary]').textContent() === selectedSummary);
ok('range context menu offers core edits', await page.getByRole('menuitem', { name: 'Play selection' }).isEnabled() && await page.getByRole('menuitem', { name: 'Ripple cut' }).isEnabled());
await page.screenshot({ path: `${OUT}/editor-range-menu.png`, fullPage: true });
await page.getByRole('menuitem', { name: 'Play selection' }).click();
ok('Play selection starts and ends within the range', await until(async () => await page.locator('[data-editor-play]').getAttribute('aria-label') === 'Pause', 10000) && await until(async () => await page.locator('[data-editor-play]').getAttribute('aria-label') === 'Play', 10000));
await clip.click({ button: 'right', position: { x: 55, y: 35 } });
ok('right-click elsewhere selects a clip and clears the range', await page.locator('[data-editor-context-menu]').isVisible() && await page.locator('[data-selection-summary]').count() === 0 && await page.getByRole('menuitem', { name: 'Split at cursor' }).isEnabled() && await page.getByRole('menuitem', { name: 'Ripple cut' }).isDisabled());
const beforeContextSplit = await page.locator('[data-clip]').count();
await page.getByRole('menuitem', { name: 'Split at cursor' }).click();
ok('context Split edits the chosen clip', await page.locator('[data-clip]').count() > beforeContextSplit);
await edit('Undo');
await clip.focus(); await page.keyboard.press('Shift+F10');
ok('keyboard opens the waveform context menu', await page.locator('[data-editor-context-menu]').isVisible());
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Edit actions' }).click();
ok('Edit menu stays available after contextual editing', await page.getByRole('menuitem', { name: 'Ripple cut', exact: true }).isDisabled());
ok('import survives Shift selection', await page.locator('[data-track]').count() === 2);
await page.keyboard.press('Escape');
// Ruler selection also works without holding a modifier.
const ruler = await page.locator('[data-ruler]').boundingBox();
await page.mouse.move(ruler.x + 12, ruler.y + 20); await page.mouse.down(); await page.mouse.move(ruler.x + 32, ruler.y + 20, { steps: 5 }); await page.mouse.up();
await page.getByRole('button', { name: 'Edit actions' }).click();
ok('ruler drag selects time', await page.getByRole('menuitem', { name: 'Ripple cut', exact: true }).isEnabled());
ok('import survives ruler selection', await page.locator('[data-track]').count() === 2);
await page.keyboard.press('Escape');
const beforeSplit = await page.locator('[data-clip]').count();
await edit('Split');
ok('split produces another clip', await page.locator('[data-clip]').count() > beforeSplit);
ok('import survives split', await page.locator('[data-track]').count() === 2);
await edit('Undo');
ok('import survives split undo', await page.locator('[data-track]').count() === 2);
await edit('Ripple cut');
ok('ripple cut changes waveform clips', await page.locator('[data-clip]').count() > beforeSplit);
ok('import survives ripple cut', await page.locator('[data-track]').count() === 2);
await edit('Undo');
ok('import survives ripple-cut undo', await page.locator('[data-track]').count() === 2);
await page.locator('[data-track]').last().locator('[data-clip]').click();
await edit('Delete');
ok('selected clip can be deleted without a range', await page.locator('[data-clip]').count() === beforeSplit - 1);
await edit('Undo');
ok('import survives clip-delete undo', await page.locator('[data-track]').count() === 2);
await page.locator('[data-track]').last().locator('[data-clip]').focus();
await page.keyboard.press('Delete');
ok('Delete shortcut edits a focused clip', await page.locator('[data-clip]').count() === beforeSplit - 1);
await page.keyboard.press('Control+z');
ok('undo shortcut restores the deleted clip', await page.locator('[data-clip]').count() === beforeSplit);
ok('import survives shortcut undo', await page.locator('[data-track]').count() === 2);
// Split, move the right clip into its left neighbor, and reopen the saved join.
await clip.click({ position: { x: 40, y: 35 } });
await edit('Split');
const right = page.locator('[data-track]').first().locator('[data-clip]').last();
await right.click({ position: { x: 20, y: 35 } });
await page.getByLabel('Timeline position').fill('0:04.000'); await page.getByLabel('Timeline position').press('Tab');
ok('overlapping clip edges show a crossfade', await page.locator('[data-crossfade]').count() === 1);
await page.screenshot({ path: `${OUT}/editor-crossfade.png`, fullPage: true });
await edit('Undo');
ok('undo removes the overlap and its fade', await page.locator('[data-crossfade]').count() === 0);
await edit('Redo');
ok('redo restores the overlap fade', await page.locator('[data-crossfade]').count() === 1);
ok('import survives crossfade undo and redo', await page.locator('[data-track]').count() === 2);
ok('crossfade autosave confirms', await until(async () => await page.locator('[data-save-state]').getAttribute('data-save-state') === 'saved'));
ok('import remains after crossfade edits', await page.locator('[data-track]').count() === 2);
await page.reload(); await page.waitForSelector('[data-editor]');
ok('saved crossfade reopens', await page.locator('[data-crossfade]').count() === 1);
ok('import persists after reopening', await page.locator('[data-track]').count() === 2);
if (await page.locator('[data-track]').count() !== 2) throw new Error('Imported track disappeared before export');
await tool('Loudness');
await page.getByRole('button', { name: 'Analyze mix' }).click();
ok('full mix loudness analysis completes', await until(async () => await page.getByText('Analysis complete', { exact: true }).isVisible(), 120000));
await page.screenshot({ path: `${OUT}/editor-loudness.png`, fullPage: true });
await page.getByRole('button', { name: 'Apply loudness' }).click();
await page.locator('[data-editor-play]').click();
ok('full-session player starts', await until(async () => (await page.locator('[data-editor-play]').getAttribute('aria-label')) === 'Pause'));
ok('pause is drawn as an icon', await page.locator('[data-editor-play] svg rect').count() === 2);
await page.locator('[data-editor-play]').click();
await tool('Loudness');
await page.getByRole('checkbox', { name: 'Listen to mastered mix' }).check();
await page.getByRole('button', { name: 'Apply loudness' }).click();
await page.locator('[data-editor-play]').click();
ok('mastered preview drives the output L/R meters', await until(async () => {
  const left = await page.getByRole('meter', { name: 'Master left level' }).getAttribute('aria-valuetext');
  const right = await page.getByRole('meter', { name: 'Master right level' }).getAttribute('aria-valuetext');
  return left !== '−∞ dBFS' && right !== '−∞ dBFS';
}, 15000));
await page.getByRole('button', { name: 'Stop', exact: true }).click();
await tool('Loudness');
await page.getByRole('checkbox', { name: 'Listen to mastered mix' }).uncheck();
await page.getByRole('button', { name: 'Apply loudness' }).click();
// Trimming an imported clip must not truncate its raw export.
await page.locator('[data-track]').nth(1).locator('[data-clip]').first().focus();
await page.keyboard.press('Enter');
await page.getByLabel('Source out').fill('0:00.100'); await page.getByLabel('Source out').press('Tab');
await page.locator('[data-export-open]').click();
ok('compact export has fixed WAV and two options', await page.getByText('Finished WAV', { exact: true }).isVisible() && (await page.locator('#export-title').count()) === 1);
await page.getByText('Include raw tracks', { exact: true }).click();
await page.screenshot({ path: `${OUT}/editor-export.png`, fullPage: true });
const [download] = await Promise.all([page.waitForEvent('download', { timeout: 120000 }), page.locator('dialog').getByRole('button', { name: 'Export', exact: true }).click()]);
const zipPath = `${OUT}/editor-project.zip`; await download.saveAs(zipPath);
const files = execSync(`unzip -Z1 '${zipPath}'`).toString().trim().split('\n');
ok('export contains finished, host raw, and imported raw files', files.some((x) => x.endsWith('_Finished.wav')) && files.some((x) => x.endsWith('_Host_raw.wav')) && files.some((x) => x.includes('sting_wav_raw.wav')), files.join(' | '));
const rawDuration = Number(execFileSync('python3', ['-c', 'import io,sys,wave,zipfile; z=zipfile.ZipFile(sys.argv[1]); name=next(n for n in z.namelist() if "sting_wav_raw.wav" in n); w=wave.open(io.BytesIO(z.read(name))); print(w.getnframes()/w.getframerate())', zipPath]).toString());
ok('raw import preserves audio beyond the trimmed clip', rawDuration > .1);
ok('completion offers sessions, repeat download, and future AI tools', await page.getByText('Your export is ready').isVisible() && await page.getByText('Back to sessions').isVisible() && await page.getByText('Download again').isVisible() && await page.getByText('Optional AI tools').isVisible());
await page.keyboard.press('Escape');
await page.locator('[data-track]').last().getByRole('button', { name: /track actions/ }).click();
await page.getByRole('menuitem', { name: 'Remove track' }).click();
ok('track removal requires confirmation', await page.getByText('Remove track?', { exact: true }).isVisible());
ok('remove dialog footer has a surface background', await page.locator('[data-slot="alert-dialog-footer"]').evaluate((node) => getComputedStyle(node).backgroundColor !== 'rgba(0, 0, 0, 0)'));
await page.screenshot({ path: `${OUT}/editor-remove-dialog-light.png`, fullPage: true });
await page.emulateMedia({ colorScheme: 'dark' });
ok('remove dialog is legible in dark mode', await until(async () => await page.locator('[data-slot="alert-dialog-content"]').evaluate((node) => getComputedStyle(node).backgroundColor === 'rgb(25, 26, 48)' && getComputedStyle(node).color === 'rgb(245, 245, 250)'), 2000));
await page.screenshot({ path: `${OUT}/editor-remove-dialog-dark.png`, fullPage: true });
await page.emulateMedia({ colorScheme: 'light' });
await page.getByRole('button', { name: 'Remove track', exact: true }).click();
ok('removed import leaves the finished timeline', await page.locator('[data-track]').count() === 1);
ok('track removal autosaves', await until(async () => await page.locator('[data-save-state]').getAttribute('data-save-state') === 'saved'));
await page.reload(); await page.waitForSelector('[data-editor]');
ok('removed track stays removed after reopen', await page.locator('[data-track]').count() === 1);
await page.locator('[data-export-open]').click();
const [removedDownload] = await Promise.all([page.waitForEvent('download', { timeout: 120000 }), page.locator('dialog').getByRole('button', { name: 'Export', exact: true }).click()]);
const removedZipPath = `${OUT}/editor-removed-track.zip`; await removedDownload.saveAs(removedZipPath);
const removedFiles = execSync(`unzip -Z1 '${removedZipPath}'`).toString().trim().split('\n');
ok('removed imported track stays out of raw ZIP while host raw remains', removedFiles.some((name) => name.endsWith('_Host_raw.wav')) && !removedFiles.some((name) => name.includes('sting_wav_raw.wav')));
await page.keyboard.press('Escape');
await tool('Restore sting.wav');
ok('source can be restored after reopen', await until(async () => await page.locator('[data-track]').count() === 2));

// A fresh browser has no OPFS takes: direct access must discover the server host.
const isolated = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1440, height: 900 } });
const remotePage = await isolated.newPage();
await remotePage.goto(`${B}/episodes/142/editor`);
await remotePage.waitForSelector('[data-editor]', { timeout: 30000 });
ok('server-only recording opens directly', remotePage.url().includes('/editor?take='));
ok('session switcher is visible', await remotePage.getByLabel('Recorded session').isVisible());
ok('server-only recording generates a waveform', await until(async () => await remotePage.locator('[data-waveform-peak]').count() > 0));
await remotePage.goto(`${B}/episodes/142/editor?take=missing-session`);
ok('missing explicit session never substitutes another', await until(async () => (await remotePage.locator('[data-loading]').textContent()).includes('unavailable')) && remotePage.url().includes('missing-session'));
await remotePage.goto(B);
ok('episode library has a direct editor action', await remotePage.locator('[data-editor-entry]').first().isVisible());
await isolated.close();
const phone = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
const mobile = await phone.newPage();
await mobile.goto(page.url());
await mobile.waitForURL('**/saved?take=*');
ok('phone falls back to Session saved', mobile.url().includes('/saved?take='));

ok('no editor page errors', !errors.length, errors.join(' | '));
console.log(fails ? `${fails} FAILED` : 'ALL PASS');
process.exitCode = fails ? 1 : 0;
await phone.close(); await browser.close();
