// Mic check as steps (1a/1b): Input → Level → Test → Noise, the test in the bar, Start recording.
import { resetSettings } from './steps.mjs';
import { chromium } from './auth.mjs';
import { OUT as S, B, DATA, FIX, TOOLS, CHROME } from './env.mjs';
const D = `${S}/flow`;
let fails = 0; const ok = (n, c, x = '') => { if (!c) fails++; console.log(c ? 'PASS' : 'FAIL', n, x); };
const until = async (fn, ms = 15000) => { const t = Date.now(); while (Date.now() - t < ms) { if (await fn().catch(() => false)) return true; await new Promise((r) => setTimeout(r, 200)); } return false; };
const browser = await chromium.launch({ executablePath: CHROME,
  args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', `--use-file-for-fake-audio-capture=${S}/voice-noisy.wav`, '--autoplay-policy=no-user-gesture-required'] });
const ctx = await browser.newContext({ ignoreHTTPSErrors: true, permissions: ['microphone'], viewport: { width: 1300, height: 900 } });
await ctx.addInitScript(() => { window.__starts = []; const o = AudioBufferSourceNode.prototype.start; AudioBufferSourceNode.prototype.start = function (when) { window.__starts.push({ buf: this.buffer, when }); return o.apply(this, arguments); }; });
const page = await ctx.newPage();
const errs = []; page.on('pageerror', (e) => errs.push(e.stack.split('\n').slice(0, 5).join(' / ')));
const text = (s) => page.textContent(s).then((t) => t.trim());
await page.goto(B + '/settings/recording');
await resetSettings(page, (s) => { s.recording ??= {}; s.recording.noiseSuppression = 0; return s; });
await page.goto(B + '/episodes/142/mic-check');
await page.waitForSelector('[data-step-tab]');
ok('four tabs, all open (a check, not a gate)', (await page.locator('[data-step-tab]').count()) === 4 && !(await page.isDisabled('[data-step-tab=noise]')));
ok('Input: the mic list', (await page.locator('[data-mic] option').count()) > 0 && (await text('[data-step-title]')) === 'Microphone');
ok('bar: record a test first, play disabled', (await text('[data-chain]')) === 'Record a test first' && (await page.isDisabled('[data-play]')));
await page.screenshot({ path: `${D}/mic-01-input.png` });
await page.click('button[data-next]');
ok('Level: meter and status', (await text('[data-step-title]')) === 'Level' && (await page.locator('[data-seg]').count()) === 28);
ok('level check comes in', await until(async () => !/Waiting…/.test(await text('[data-check="0"] [data-value]')), 10000), await text('[data-check="0"] [data-value]'));
await page.screenshot({ path: `${D}/mic-02-level.png` });
await page.click('button[data-next]');
ok('Test step', (await text('[data-step-title]')) === 'Test recording' && /Not done yet/.test(await text('[data-check="5"] [data-value]')));
await page.click('[data-test-btn]');
await page.waitForSelector('[data-test-result]:not([hidden])', { timeout: 20000 });
ok('test measured', /Peak −\d+\.\d dBFS/.test(await text('[data-test-result]')), await text('[data-test-result]'));
ok('bar can play the test', !(await page.isDisabled('[data-play]')) && (await text('[data-chain]')) === 'Test recording');
await page.click('[data-play]');
ok('plays ~10 s', await until(async () => (await page.getAttribute('[data-play]', 'aria-label')) === 'Pause preview', 5000) && / \/ 0:1[01]$|\/ 0:09$/.test(await text('[data-time]')), await text('[data-time]'));
await page.click('[data-play]');
await page.screenshot({ path: `${D}/mic-03-test.png` });
await page.click('button[data-next]');
ok('Noise: floor from the test', await until(async () => /dBFS/.test(await text('[data-ns-floor]')), 5000) && /Measured from your test/.test(await text('[data-ns-suggest]')), `${await text('[data-ns-floor]')} ${await text('[data-ns-suggest]')}`);
ok('Use N % offered', await page.locator('[data-ns-use]').isVisible(), await text('[data-ns-use]'));
await page.click('[data-ns-use]');
ok('Using N % once chosen', /^Using \d+ %$/.test(await text('[data-ns-use]')) && (await page.getAttribute('[data-ns-use]', 'aria-pressed')) === 'true');
const n = Number((await text('[data-ns-test-value]')).replace(' %', ''));
ok('saved as the export default', await until(async () => (await page.evaluate(() => JSON.parse(localStorage.getItem('podstudio:settings')).recording.noiseSuppression)) === n, 3000), String(n));
ok('cleaned: chain and reduction', await until(async () => (await text('[data-chain]')) === `Test recording → Noise ${n} %`, 60000) && /Background −\d+ dB/.test(await text('[data-ns-reduction]')), `${await text('[data-chain]')} · ${await text('[data-ns-reduction]')}`);
await page.click('[data-play]');
await until(async () => (await page.getAttribute('[data-play]', 'aria-label')) === 'Pause preview', 5000);
const floors = await page.evaluate(() => {
  const g = window.__starts; const last = g.at(-1).when;
  return g.filter((s) => s.when === last).map((s) => { const x = s.buf.getChannelData(0); const B = Math.round(s.buf.sampleRate / 10); const lv = []; for (let o = 0; o + B <= x.length; o += B) { let e = 0; for (let i = o; i < o + B; i++) e += x[i] * x[i]; const d = 10 * Math.log10(e / B); if (d > -100) lv.push(d); } lv.sort((a, b) => a - b); return lv[Math.floor(lv.length * 0.1)] ?? -120; });
});
ok('Cleaned is quieter between words than Original', floors.length === 3 && floors[1] < floors[0] - 8, floors.map((f) => f.toFixed(1)).join(' '));
await page.click('[data-ab] button:has-text("Removed")');
ok('Removed', (await text('[data-chain]')) === 'Only the removed noise');
await page.screenshot({ path: `${D}/mic-04-noise.png` });
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: `${D}/mic-04-noise-phone.png` });
ok('phone: no sideways scroll', !(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)));
await page.setViewportSize({ width: 1300, height: 900 });
await page.click('[data-step-tab=input]');
ok('tabs go back', (await text('[data-step-title]')) === 'Microphone');
await page.click('[data-step-tab=noise]');
ok('Start recording', (await text('button[data-next]')) === 'Start recording');
await page.click('[data-start]');
await page.waitForURL('**/recording*', { timeout: 10000 });
ok('goes to the recording screen', true);
ok('no page errors', !errs.length, errs.join(' | '));
console.log(fails ? `${fails} FAILED` : 'ALL PASS');
process.exitCode = fails ? 1 : 0;
await browser.close();
