import { chromium } from './auth.mjs';
import { B, OUT, CHROME } from './env.mjs';
let fails = 0;
const ok = (name, condition) => { if (!condition) fails++; console.log(condition ? 'PASS' : 'FAIL', name); };
const browser = await chromium.launch({ executablePath: CHROME, args: ['--autoplay-policy=no-user-gesture-required', '--disable-audio-output'] });
const ctx = await browser.newContext({ ignoreHTTPSErrors: true, acceptDownloads: true, viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
const page = await ctx.newPage(); const errors = []; page.on('pageerror', (e) => errors.push(e.message));
await page.goto(B);
await page.evaluate(async () => {
  const rate = 48000, pcm = new Int16Array(rate * 12);
  for (let n = 0; n < pcm.length; n++) pcm[n] = Math.round(Math.sin(n * 2 * Math.PI * 220 / rate) * 5000);
  const put = async (url, body, json = true) => { const r = await fetch(url, { method: 'PUT', headers: json ? { 'Content-Type': 'application/json' } : {}, body: json ? JSON.stringify(body) : body }); if (!r.ok) throw new Error(`Seed: ${r.status}`); };
  for (const [id, speaker] of [['mobile-review-host', 'Host'], ['mobile-review-guest', 'Sam']]) {
    const meta = { id, episodeId: '142', name: 'Mobile review', kind: 'session', speaker, number: 1, startLine: 0, startText: '', device: 'Fixture', sampleRate: rate, bitDepth: 16, channels: 1, samples: pcm.length, segments: 3, startedAt: Date.now(), updatedAt: Date.now(), status: 'done', group: 'mobile-review-group', peaks: Array(24).fill(.2), markers: [{ kind: 'retake', t: 3, line: 0 }, { kind: 'cut', t: 5, end: 6, who: 'host' }] };
    await put(`/api/takes/${id}`, { meta, done: false });
    for (let n = 0; n < 3; n++) await put(`/api/takes/${id}/segments/${n + 1}`, pcm.slice(n * rate * 4, (n + 1) * rate * 4).buffer, false);
    await put(`/api/takes/${id}`, { meta, done: true });
  }
});
await page.goto(`${B}/episodes/142/editor?take=mobile-review-host`);
await page.waitForURL('**/saved?take=mobile-review-host');
await page.waitForSelector('[data-recording-review]');
ok('server-only phone session opens review', await page.getByText('Full editing and finished-mix export', { exact: false }).isVisible());
ok('host and guest raw downloads available', await page.locator('[data-raw-download]').count() === 2);
ok('no desktop editor loop', await page.locator('[data-desktop-editor]').isHidden());
await page.getByRole('button', { name: 'Play recording', exact: true }).click();
await page.getByRole('button', { name: 'Pause recording', exact: true }).waitFor();
ok('bounded preview plays', await page.locator('[data-review-audio]').evaluate((a) => !a.paused && a.duration <= 30));
await page.getByLabel('Recording position').evaluate((input) => { input.value = '5'; input.dispatchEvent(new Event('change', { bubbles: true })); });
await page.waitForTimeout(500);
ok('scrub position applies', (await page.locator('[data-review-time]').textContent()).startsWith('0:05'));
await page.getByRole('button', { name: 'Pause recording', exact: true }).click();
const [raw] = await Promise.all([page.waitForEvent('download'), page.locator('[data-raw-download]').first().click()]);
await raw.saveAs(`${OUT}/mobile-host-raw.wav`);
ok('raw host download succeeds', raw.suggestedFilename().endsWith('_Host_raw.wav'));
await ctx.setOffline(true);
await page.getByRole('button', { name: 'Retry synchronization' }).click();
ok('offline status is explicit', (await page.locator('[data-review-server]').textContent()).includes('Waiting for connection'));
await ctx.setOffline(false); await page.waitForTimeout(500);
await page.screenshot({ path: `${OUT}/review-phone.png`, fullPage: true });
await page.setViewportSize({ width: 844, height: 390 });
ok('landscape remains mobile', await page.locator('[data-desktop-editor]').isHidden());
ok('landscape has no overflow', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
await page.waitForTimeout(300);
await page.screenshot({ path: `${OUT}/review-landscape.png`, fullPage: true });
await page.goto(`${B}/episodes/142/saved?take=missing-recording`);
await page.getByRole('button', { name: 'Retry', exact: true }).waitFor();
ok('explicit missing session is preserved', await page.getByRole('button', { name: 'Retry', exact: true }).isVisible() && page.url().includes('missing-recording'));
await page.goto(`${B}/settings/pads`);
ok('mobile pad setup is unavailable', await page.getByText('Configure sound pads on desktop.', { exact: false }).isVisible());
ok('mobile Settings hides pad navigation', await page.locator('nav a[href="/settings/pads"]').isHidden());
await page.goto(`${B}/episodes/142/recording`);
ok('mobile has no visible pad controls', await page.locator('[data-pad-strip]').isHidden() && await page.locator('[data-pad-rail]').isHidden() && await page.locator('[data-pads-setup]').isHidden());
await page.goto(B);
ok('library uses review action', await page.locator('[data-editor-entry]').first().textContent().then((s) => s === 'Review recording'));
ok('no page errors', !errors.length);
console.log(fails ? `${fails} FAILED` : 'ALL PASS'); process.exitCode = fails ? 1 : 0;
await browser.close();
