import { resetSettings } from './steps.mjs';
import { chromium } from './auth.mjs';
import { OUT as S, B, DATA, FIX, TOOLS, CHROME } from './env.mjs';
const browser = await chromium.launch({ executablePath: CHROME,
  args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', `--use-file-for-fake-audio-capture=${FIX}/noisy-guest.wav`, '--autoplay-policy=no-user-gesture-required'] });
const ctx = await browser.newContext({ ignoreHTTPSErrors: true,  viewport: { width: 1300, height: 900 }, permissions: ['microphone'] });
const page = await ctx.newPage();
const errs = []; page.on('pageerror', (e) => errs.push(e.message));
let fails = 0; const ok = (n, c, x = '') => { if (!c) fails++; console.log(c ? 'PASS' : 'FAIL', n, x); };
await page.goto(B + '/episodes/142/script'); await resetSettings(page, () => ({}), { clear: true });
await page.goto(B + '/episodes/142/recording?legacy=1');
await page.waitForTimeout(1500);
await page.click('[data-start]');
await page.waitForTimeout(70000);
await page.keyboard.press('m'); await page.click('[data-end]'); await page.click('dialog [value=end]');
await page.waitForURL('**/saved?take=*'); await page.waitForTimeout(800);
await page.getByRole('button', { name: /^(Play|Pause) recording$/ }).click();
await page.waitForTimeout(500);
const src0 = await page.evaluate(() => document.querySelector('[data-review-audio]').src);
const bounded = await page.evaluate(() => document.querySelector('[data-review-audio]').duration);
ok('review playback uses a bounded window', bounded <= 30.01);
// Reach the rolling window edge without another 30 seconds of fixture time.
await page.evaluate(() => document.querySelector('[data-review-audio]').currentTime = 29.5);
await page.waitForTimeout(2000);
const next = await page.evaluate(() => { const a = document.querySelector('[data-review-audio]'); return { src: a.src, t: a.currentTime, paused: a.paused }; });
ok('review continues into the next window', next.src !== src0 && !next.paused, JSON.stringify(next));
await page.getByLabel('Recording position').fill('45');
await page.waitForTimeout(1000);
ok('scrubbing continues from a later point', (await page.locator('[data-review-time]').textContent()).match(/0:4[5-7]/), await page.locator('[data-review-time]').textContent());
// Sessions list: the card still offers the existing noise preview.
await page.goto(B + '/episodes/142/sessions');
await page.waitForTimeout(1500);
await page.locator('[data-card] label:has-text("Noise suppression")').first().click();
for (let i = 0; i < 120 && !/^Cleaned · 40%/.test(await page.locator('[data-card] [data-ns-status]').first().textContent()); i++) await page.waitForTimeout(1000);
ok('sessions card prepares the cleaned copy', /^Cleaned · 40%/.test(await page.locator('[data-card] [data-ns-status]').first().textContent()), await page.locator('[data-card] [data-ns-status]').first().textContent());
await page.screenshot({ path: `${S}/ns/sessions-toggle.png` });
ok('no page errors', !errs.length, errs.join('; '));
console.log(fails ? `${fails} FAILED` : 'ALL PASS');
process.exitCode = fails ? 1 : 0;
await browser.close();
