import { resetSettings } from './steps.mjs';
import { chromium } from './auth.mjs';
import { OUT as S, B, DATA, FIX, TOOLS, CHROME } from './env.mjs';
const browser = await chromium.launch({ executablePath: CHROME,
  args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', `--use-file-for-fake-audio-capture=${FIX}/noisy-guest.wav`, '--autoplay-policy=no-user-gesture-required'] });
const ctx = await browser.newContext({ ignoreHTTPSErrors: true,  viewport: { width: 1300, height: 900 }, permissions: ['microphone'] });
const page = await ctx.newPage();
const errs = []; page.on('pageerror', (e) => errs.push(e.message));
let fails = 0; const ok = (n, c, x = '') => { if (!c) fails++; console.log(c ? 'PASS' : 'FAIL', n, x); };
await page.goto(B + '/episodes/142/script'); await resetSettings(page, () => ({}), { clear: true });
await page.goto(B + '/episodes/142/recording');
await page.waitForTimeout(1500);
await page.click('[data-start]');
await page.waitForTimeout(70000);
await page.keyboard.press('m'); await page.click('[data-end]'); await page.click('dialog [value=end]');
await page.waitForURL('**/saved?take=*'); await page.waitForTimeout(800);
await page.click('[data-play]');
await page.waitForTimeout(500);
const src0 = await page.evaluate(() => document.querySelector('[data-player]').src);
await page.evaluate(() => (document.querySelector('[data-player]').currentTime = 20));
await page.click('[data-ab] button:has-text("Cleaned")');
const tClick = Date.now();
for (let i = 0; i < 40 && !/Cleaned from here/.test(await page.locator('[data-chain]').textContent()); i++) await page.waitForTimeout(250);
console.log('cleaned audio playing after', ((Date.now() - tClick) / 1000).toFixed(1), 's');
const st1 = await page.locator('[data-chain]').textContent();
const p1 = await page.evaluate(() => { const a = document.querySelector('[data-player]'); return { src: a.src, t: a.currentTime, d: a.duration, paused: a.paused }; });
ok('a cleaned stretch from where you are plays within seconds', p1.src !== src0 && p1.d <= 13 && p1.t < 12 && !p1.paused, `${st1} · ${JSON.stringify(p1)}`);
const t0 = Date.now();
for (let i = 0; i < 120 && !/^Cleaned · /.test(await page.locator('[data-chain]').textContent()); i++) await page.waitForTimeout(1000);
const p2 = await page.evaluate(() => { const a = document.querySelector('[data-player]'); return { src: a.src, t: a.currentTime, d: a.duration, paused: a.paused }; });
ok('swaps to the whole cleaned session', /^Cleaned · 40%/.test(await page.locator('[data-chain]').textContent()) && p2.d > 65 && !p2.paused, `after ${((Date.now() - t0) / 1000).toFixed(0)} s · ${JSON.stringify(p2)}`);
await page.click('[data-ab] button:has-text("Original")');
await page.waitForTimeout(500);
const p3 = await page.evaluate(() => { const a = document.querySelector('[data-player]'); return { src: a.src, t: a.currentTime }; });
ok('off goes back to the original at the same moment', p3.src === src0 && Math.abs(p3.t - p2.t) < 3, JSON.stringify(p3));
// Sessions list: the cleaned copy is cached, so the card's toggle is instant.
await page.goto(B + '/episodes/142/sessions');
await page.waitForTimeout(1500);
await page.locator('[data-card] label:has-text("Noise suppression")').first().click();
await page.waitForTimeout(1500);
ok('sessions card uses the cached cleaned copy', /^Cleaned · 40%/.test(await page.locator('[data-card] [data-ns-status]').first().textContent()), await page.locator('[data-card] [data-ns-status]').first().textContent());
await page.screenshot({ path: `${S}/ns/sessions-toggle.png` });
ok('no page errors', !errs.length, errs.join('; '));
console.log(fails ? `${fails} FAILED` : 'ALL PASS');
process.exitCode = fails ? 1 : 0;
await browser.close();
