import { toStep, pickAndDownload } from './steps.mjs';
import { chromium } from './auth.mjs';
import { execSync } from 'node:child_process';
import { OUT as S, B, DATA, FIX, TOOLS, CHROME } from './env.mjs';
const e = '/episodes/142';
let fails = 0;
const ok = (n, c, x = '') => { if (!c) fails++; console.log(c ? 'PASS' : 'FAIL', n, x); };
const until = async (fn, ms = 15000) => { const t = Date.now(); while (Date.now() - t < ms) { if (await fn()) return true; await new Promise((r) => setTimeout(r, 250)); } return false; };
const errs = [];
const browser = await chromium.launch({ executablePath: CHROME, args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', `--use-file-for-fake-audio-capture=${FIX}/mono11.wav`, '--autoplay-policy=no-user-gesture-required'] });
const actx = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1300, height: 850 }, permissions: ['microphone'], acceptDownloads: true });
const a = await actx.newPage();
a.on('pageerror', (x) => errs.push('A ' + x.message));
a.on('dialog', (d) => d.accept());
await a.goto(B + e + '/recording');
await a.waitForTimeout(2000);
await a.click('[data-start]');
ok('saved to server while recording', await until(async () => /Saved to server/.test(await a.locator('[data-saved]').textContent()), 15000), await a.locator('[data-saved]').textContent());
// Offline for a while: it says "in this browser", then catches up.
await actx.setOffline(true);
ok('offline: saved in this browser', await until(async () => /Saved in this browser/.test(await a.locator('[data-saved]').textContent()), 20000), await a.locator('[data-saved]').textContent());
await actx.setOffline(false);
ok('back online: to the server again', await until(async () => /Saved to server/.test(await a.locator('[data-saved]').textContent()), 30000), await a.locator('[data-saved]').textContent());
await a.keyboard.press('r');
await a.waitForTimeout(3000);
await a.keyboard.press('m');
await a.click('[data-end]');
await a.click('dialog [value=end]');
await a.waitForURL('**/saved?take=*');
const takeId = new URL(a.url()).searchParams.get("take");
ok('saved page: all of it on the server', await until(async () => (await a.locator('[data-server]').textContent()) === 'All of it'), await a.locator('[data-server]').textContent());
const local = await a.evaluate(async (id) => {
  const root = await navigator.storage.getDirectory();
  const dir = await (await root.getDirectoryHandle('takes')).getDirectoryHandle(id);
  const file = await (await dir.getFileHandle('meta.json')).getFile();
  return JSON.parse(await file.text());
}, takeId);
const server = await a.evaluate(async (id) => (await fetch(`/api/takes/${id}`)).json(), takeId);
ok('server has every piece, marked done', server.segments === local.segments && server.done && server.meta.markers.some((m) => m.kind === 'retake'), `${server.segments}/${local.segments}`);

// Another browser: the session is on the server; bring it in and export it.
const bctx = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1300, height: 850 }, acceptDownloads: true });
const b = await bctx.newPage();
b.on('pageerror', (x) => errs.push('B ' + x.message));
await b.goto(B + e + '/sessions');
ok('other browser lists it as on the server', await until(async () => (await b.locator(`[data-server-take="${takeId}"]`).count()) === 1));
await b.click(`[data-server-take="${takeId}"] button`);
await b.waitForURL(`**/sessions?take=${takeId}`);
ok('brought in: a session card', await until(async () => (await b.locator(`[data-card="${takeId}"]`).count()) === 1));
await b.goto(`${B}${e}/session?take=${takeId}`);
await toStep(b, 'export');
const [dl] = await Promise.all([b.waitForEvent('download'), pickAndDownload(b)]);
execSync(`rm -rf ${S}/uploads/x && mkdir -p ${S}/uploads/x`);
await dl.saveAs(`${S}/uploads/x/s.zip`);
execSync(`cd ${S}/uploads/x && unzip -q s.zip`);
const secs = Number(execSync(`python3 -c "import wave,glob;w=wave.open([f for f in glob.glob('${S}/uploads/x/*.wav') if not f.endswith('_edit.wav')][0]);print(w.getnframes()/w.getframerate())"`).toString());
ok('exported WAV is the whole recording', Math.abs(secs - local.samples / local.sampleRate) < 0.01, `${secs.toFixed(2)} s`);
ok('no page errors', !errs.length, errs.join('\n'));
console.log(fails ? `${fails} FAILED` : 'ALL PASS');
process.exitCode = fails ? 1 : 0;
await browser.close();
