<script lang="ts">
  import {onMount,onDestroy} from 'svelte';
  import {Tabs} from 'bits-ui';
  import {api} from '@/lib/api';
  import {emptyPackage,transcriptFiles,subtitleTime,type EpisodePackageV1,type GenerationJob,type GenerationSection} from '@/lib/episode-package';
  import {preparedWav,prepareTranscription,sliceWav} from '@/lib/prepared-audio';
  import {encodeMp3} from '@/lib/audio/mp3';
  import {decodeToLibraryRate,saveLibraryFile} from '@/lib/pads';
  import {openRecordingReview} from '@/lib/recording-review';
  import {zip,download,type ZipEntry} from '@/lib/zip';
  import {isMobile} from '@/lib/mobile';
  import {beginSave} from '@/lib/save-status';
  import {Button} from '@/components/shadcn/button';
  import {Input} from '@/components/shadcn/input';
  import {Checkbox} from '@/components/shadcn/checkbox';
  import * as Field from '@/components/shadcn/field';
  import Spinner from '@/components/shadcn/spinner/Spinner.svelte';
  let {episodeId,title}:{episodeId:string;title:string}=$props();
  let pkg=$state<EpisodePackageV1>(emptyPackage(episodeId)),revision=$state(0),valid=$state(false),available=$state(false),current=$state(false),loaded=$state(false),error=$state(''),progress=$state(''),busy=$state(false),job=$state<GenerationJob|null>(null),search=$state(''),mp3=$state(false),raw=$state(false),tab=$state('title'),dirty=$state(false),userId=$state(0);
  const draftKey=()=>`podstudio-package-${userId}-${episodeId}`;
  let player=$state<HTMLAudioElement>();
  let controller:AbortController|null=null,timer:ReturnType<typeof setTimeout>,saveTimer:ReturnType<typeof setTimeout>,disposed=false,loopEnd:number|null=null;
  let mobile=$state(false);
  const sections:GenerationSection[]=['title','description','chapters','soundbites','transcript'];
  const textArea='w-full min-h-24 rounded-lg border border-border bg-control p-3 text-sm focus-visible:outline-2 focus-visible:outline-primary';
  const timedStale=(section:'transcript'|'chapters'|'soundbites')=>!current||pkg.timingFingerprints[section]!==pkg.source?.fingerprint;
  async function reload(){const r=await api<{package:EpisodePackageV1;revision:number;userId:number;sourceAvailable:boolean;sourceCurrent:boolean}>(`episode-packages/${episodeId}`);pkg=r.package;revision=r.revision;userId=r.userId;available=r.sourceAvailable;current=r.sourceCurrent;if(!pkg.materials.title)pkg.materials.title=title;}
  onMount(async()=>{mobile=isMobile();try{await reload();valid=(await api<{valid:boolean}>('me/ai')).valid;const jobs=await api<{jobs:GenerationJob[]}>(`generation-jobs?episode=${episodeId}`);job=jobs.jobs[0]??null;if(job&&['queued','transcribing','writing'].includes(job.state))void poll();}catch(e){error=(e as Error).message;}finally{loaded=true;}});
  onDestroy(()=>{disposed=true;clearTimeout(timer);clearTimeout(saveTimer);controller?.abort();player?.pause();});
  async function save(){clearTimeout(saveTimer);const sent=JSON.stringify($state.snapshot(pkg));const finish=beginSave();try{const r=await api<{revision:number}>(`episode-packages/${episodeId}`,{method:'PUT',body:{baseRevision:revision,package:$state.snapshot(pkg)}});revision=r.revision;if(sent===JSON.stringify($state.snapshot(pkg))){dirty=false;localStorage.removeItem(draftKey());}finish('saved');}catch(e){error=(e as Error).message;finish(navigator.onLine?'error':'waiting');localStorage.setItem(draftKey(),JSON.stringify($state.snapshot(pkg)));}}
  function changed(){dirty=true;localStorage.setItem(draftKey(),JSON.stringify($state.snapshot(pkg)));clearTimeout(saveTimer);saveTimer=setTimeout(save,600);}
  async function recover(){const saved=localStorage.getItem(draftKey());if(!saved)return;const local=JSON.parse(saved);await reload();pkg.materials=local.materials;pkg.timingFingerprints=local.timingFingerprints;await save();}
  function accept(section:GenerationSection,value?:string){if(!pkg.suggestions)return;const s=pkg.suggestions;if(section==='title')pkg.materials.title=value??s.titles[0];else if(section==='description')pkg.materials.description=s.description;else if(section==='chapters'){pkg.materials.chapters=structuredClone($state.snapshot(s.chapters));pkg.timingFingerprints.chapters=s.fingerprint;}else if(section==='transcript'){pkg.materials.transcript=structuredClone($state.snapshot(s.transcript));pkg.timingFingerprints.transcript=s.fingerprint;}else if(section==='soundbites'){pkg.materials.soundbites=structuredClone($state.snapshot(s.soundbites));pkg.timingFingerprints.soundbites=s.fingerprint;}changed();}
  async function poll(){if(!job||disposed)return;try{job=await api(`generation-jobs/${job.id}`);if(job?.state==='completed'){const draft=dirty?$state.snapshot(pkg):null;await reload();if(draft){pkg.materials=draft.materials;pkg.timingFingerprints=draft.timingFingerprints;await save();}valid=(await api<{valid:boolean}>('me/ai')).valid;}else if(job&&['queued','transcribing','writing'].includes(job.state))timer=setTimeout(poll,2000);}catch(e){error=(e as Error).message;}}
  async function generate(section:GenerationSection){if(!pkg.source)return;busy=true;error='';controller=new AbortController();try{await save();if(error)throw new Error(error);const asset=await api<{manifest:string}>(`prepared-audio/${pkg.source.audioId}`);if(!JSON.parse(asset.manifest).length){if(mobile)throw new Error('Open this episode on desktop to prepare transcription audio.');const wav=await preparedWav(pkg.source.audioId,s=>progress=s,controller.signal);await prepareTranscription(pkg.source.audioId,wav,s=>progress=s,controller.signal);}const id=crypto.randomUUID();await api('generation-jobs',{body:{id,episodeId,audioId:pkg.source.audioId,section}});job={id,state:'queued',section,progress:'Waiting to generate…',error:null};progress='';void poll();}catch(e){if(!controller.signal.aborted)error=(e as Error).message;}finally{busy=false;}}
  async function cancel(){controller?.abort();if(job)await api(`generation-jobs/${job.id}`,{method:'DELETE'});await poll();busy=false;progress='';}
  function seek(start:number,end?:number){if(!player)return;loopEnd=end??null;player.currentTime=start;void player.play().catch(e=>error=e.message);}
  async function bite(id:string,library=false){const item=pkg.materials.soundbites.find(s=>s.id===id);if(!item||!pkg.source)return;busy=true;error='';try{const wav=await preparedWav(pkg.source.audioId,s=>progress=s);const clip=await sliceWav(wav,item.start,item.end);if(library){progress='Saving independent library clip…';await saveLibraryFile(await decodeToLibraryRate(await clip.arrayBuffer()),{id:`f${crypto.randomUUID().replaceAll('-','')}`,name:item.title,source:'Saved soundbite'});}else download(clip,`${item.title||'Soundbite'}.wav`);}catch(e){error=(e as Error).message;}finally{busy=false;progress='';}}
  async function packageDownload(){busy=true;error='';controller=new AbortController();try{await save();const m=pkg.materials;const entries:ZipEntry[]=[{name:'Title.txt',data:m.title},{name:'Description.txt',data:m.description}];if(pkg.source&&available){const wav=await preparedWav(pkg.source.audioId,s=>progress=s,controller.signal);entries.push({name:'Finished.wav',data:wav});if(mp3)entries.push({name:'Finished.mp3',data:await encodeMp3(wav,m.title,d=>progress=`Encoding MP3… ${Math.round(d*100)}%`)});if(!timedStale('soundbites'))for(const s of m.soundbites.filter(s=>s.selected)){const clip=await sliceWav(wav,s.start,s.end);entries.push({name:`Soundbites/${s.id}.wav`,data:clip});if(mp3)entries.push({name:`Soundbites/${s.id}.mp3`,data:await encodeMp3(clip,s.title)});}}
    if(!timedStale('chapters')){entries.push({name:'Chapters.json',data:JSON.stringify(m.chapters,null,2)},{name:'Chapters.txt',data:m.chapters.map(c=>`${subtitleTime(c.start)} ${c.title}`).join('\n')});}
    if(!timedStale('transcript')){const t=transcriptFiles(m.transcript);entries.push({name:'Transcript.txt',data:t.txt},{name:'Transcript.srt',data:t.srt},{name:'Transcript.vtt',data:t.vtt});}
    if(raw&&pkg.source&&available){const recording=await openRecordingReview(episodeId,pkg.source.takeId);for(const entry of recording.downloads){controller.signal.throwIfAborted();entries.push({name:`Raw/${entry.id.replace(/[^A-Za-z0-9_-]/g,'_')}.wav`,data:await entry.blob(s=>progress=s)});}}
    progress='Building episode package…';download(await zip(entries),`Episode-${episodeId}.zip`);
  }catch(e){error=(e as Error).message;}finally{busy=false;progress='';}}
</script>
<div class="mx-auto grid max-w-5xl gap-5 p-4 sm:p-6" data-episode-preparation>
  <header class="flex flex-wrap items-center justify-between gap-3"><div><h1 class="text-xl">Prepare episode</h1><p class="mt-1 text-sm text-text-2">Review your sound and publishing materials, then download.</p></div><Button onclick={packageDownload} disabled={busy||!loaded} data-package-download>Download package</Button></header>
  {#if !loaded}<Spinner label="Loading episode"/>{:else}
    {#if pkg.source&&available}<section class="rounded-xl border border-border bg-surface p-4"><h2 class="mb-3 text-sm">Finished mix</h2><audio bind:this={player} src={`/api/prepared-audio/${pkg.source.audioId}/wav`} controls preload="metadata" class="w-full" ontimeupdate={()=>{if(loopEnd!==null&&player!.currentTime>=loopEnd){player!.pause();loopEnd=null;}}}></audio><div class="mt-3 flex items-center gap-2"><Checkbox id="package-mp3" bind:checked={mp3}/><label for="package-mp3" class="text-sm">Include MP3 and MP3 soundbites</label><Checkbox id="package-raw" bind:checked={raw}/><label for="package-raw" class="text-sm">Include raw tracks</label></div>{#if !current}<p class="mt-3 text-sm text-warn">The mix has changed. Open the editor to prepare its latest version. Outdated timestamped materials are excluded until reviewed.</p>{/if}</section>{:else}<p class="rounded-xl border border-border p-4 text-sm">{pkg.source?'This recording is unavailable. Your approved text is retained.':'Prepare a finished mix in the desktop editor to add audio.'} <a class="underline" href={`/episodes/${episodeId}/editor${pkg.source?`?take=${pkg.source.takeId}`:''}`}>{mobile?'Full editing is available on desktop.':'Open editor'}</a></p>{/if}
    <section class="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border p-4"><div class="text-sm">{valid?'Generate optional drafts from your finished edited mix.':'Add a valid API key to enable generation. Manual editing and downloads remain available.'}<p class="mt-1 text-xs text-text-2">Generating sends the prepared audio to OpenAI and uses your account’s credits.</p></div>{#if !valid}<Button variant="outline" href={`/settings/ai?next=${encodeURIComponent(`/episodes/${episodeId}/package`)}`}>Add API key</Button>{/if}<Button disabled={!valid||!available||!current||busy||!!job&&['queued','transcribing','writing'].includes(job.state)} onclick={()=>generate('all')} data-generate-all>Generate all drafts</Button></section>
    {#if job}<div class="rounded-xl border border-border p-4 text-sm" aria-live="polite">{job.progress}{#if job.error}<p class="mt-2 text-rec">{job.error}</p>{/if}{#if ['queued','transcribing','writing'].includes(job.state)}<p class="mt-2 text-text-2">Audio uploaded. You can close this page; generation continues on the server.</p><Button variant="outline" onclick={cancel}>Cancel generation</Button>{:else if ['failed','interrupted'].includes(job.state)}<Button variant="outline" onclick={async()=>{await api(`generation-jobs/${job!.id}/retry`,{body:{}});void poll();}}>Retry generation</Button>{/if}</div>{/if}
    {#if error}<div role="alert" class="rounded-lg border border-rec bg-rec/10 p-3 text-sm text-rec">{error}<Button variant="outline" onclick={async()=>{error='';await reload();}}>Reload saved version</Button></div>{/if}
    {#if typeof localStorage!=='undefined'&&localStorage.getItem(draftKey())}<Button variant="outline" onclick={recover}>Recover local text draft</Button>{/if}
    <Tabs.Root bind:value={tab}><Tabs.List class="flex flex-wrap gap-1 rounded-lg bg-control p-1" aria-label="Publishing materials">{#each sections as section}<Tabs.Trigger value={section} class="rounded-md px-4 py-2 text-sm capitalize data-[state=active]:bg-surface data-[state=active]:shadow-sm">{section}</Tabs.Trigger>{/each}</Tabs.List>
      {#each sections as section}<Tabs.Content value={section} class="mt-4 grid gap-4 rounded-xl border border-border bg-surface p-5">
        <div class="flex items-center justify-between"><h2 class="capitalize">{section}</h2><Button size="sm" variant="outline" disabled={!valid||!available||!current||busy} onclick={()=>generate(section)}>Generate {section}</Button></div>
        {#if section==='title'}<Field.Field><Field.Label for="episode-title">Approved title</Field.Label><Input id="episode-title" maxlength={300} bind:value={pkg.materials.title} oninput={changed}/></Field.Field>{#each pkg.suggestions?.titles??[] as suggestion}<div class="flex items-center justify-between gap-3 rounded-lg border border-border p-3 text-sm"><span>{suggestion}</span><Button size="sm" variant="outline" onclick={()=>accept('title',suggestion)}>Use title</Button></div>{/each}
        {:else if section==='description'}<Field.Field><Field.Label for="episode-description">Description</Field.Label><textarea id="episode-description" class={textArea} rows="8" maxlength={30000} bind:value={pkg.materials.description} oninput={changed}></textarea></Field.Field>{#if pkg.suggestions?.description}<blockquote class="whitespace-pre-wrap rounded-lg bg-control p-4 text-sm">{pkg.suggestions.description}</blockquote><Button variant="outline" onclick={()=>accept('description')}>Use suggested description</Button>{/if}
        {:else if section==='chapters'}{#if timedStale('chapters')&&pkg.materials.chapters.length}<p class="text-sm text-warn">Chapters need review against the current mix.</p>{/if}{#each pkg.materials.chapters as chapter,i}<div class="flex gap-2"><Input type="number" min="0" step=".1" aria-label={`Chapter ${i+1} start seconds`} bind:value={chapter.start} oninput={changed} class="w-28"/><Input aria-label={`Chapter ${i+1} title`} bind:value={chapter.title} oninput={changed}/><Button variant="ghost" onclick={()=>{pkg.materials.chapters.splice(i,1);changed();}}>Remove</Button></div>{/each}<Button variant="outline" onclick={()=>{pkg.materials.chapters.push({start:0,title:''});changed();}}>Add chapter</Button>{#if pkg.suggestions?.chapters.length}<p class="text-sm">{pkg.suggestions.chapters.map(c=>`${subtitleTime(c.start)} ${c.title}`).join(' · ')}</p><Button variant="outline" onclick={()=>accept('chapters')}>Use suggested chapters</Button>{/if}
        {:else if section==='transcript'}<Button variant="outline" onclick={()=>{pkg.materials.transcript.push({start:0,end:1,text:''});changed();}}>Add transcript passage</Button><Input placeholder="Search transcript" aria-label="Search transcript" bind:value={search}/>{#each pkg.materials.transcript.filter(t=>t.text.toLowerCase().includes(search.toLowerCase())) as segment}<div class="grid gap-2 sm:grid-cols-[100px_1fr]"><Button size="sm" variant="ghost" disabled={!available} onclick={()=>seek(segment.start)}>{subtitleTime(segment.start)}</Button><textarea class={textArea} rows="2" bind:value={segment.text} oninput={changed} aria-label={`Transcript at ${subtitleTime(segment.start)}`}></textarea></div>{/each}{#if pkg.suggestions?.transcript.length}<p class="text-sm">New transcript: {pkg.suggestions.transcript.length} passages. {pkg.suggestions.transcript.slice(0,2).map(t=>t.text).join(' ')}</p><Button variant="outline" onclick={()=>accept('transcript')}>Use generated transcript</Button>{/if}
        {:else if section==='soundbites'}<Button variant="outline" onclick={()=>{pkg.materials.soundbites.push({id:crypto.randomUUID(),start:0,end:Math.min(30,pkg.source?.duration??30),title:'Soundbite',selected:false});changed();}}>Add soundbite</Button>{#each pkg.materials.soundbites as item}<div class="grid gap-3 rounded-lg border border-border p-4"><Input aria-label="Soundbite title" bind:value={item.title} oninput={changed}/><div class="flex flex-wrap gap-2"><Input type="number" min="0" step=".1" class="w-28" aria-label="Soundbite start seconds" bind:value={item.start} oninput={changed}/><Input type="number" min="0" step=".1" class="w-28" aria-label="Soundbite end seconds" bind:value={item.end} oninput={changed}/><Button variant="outline" disabled={!available} onclick={()=>seek(item.start,item.end)}>Play</Button><Button variant="outline" disabled={busy||!available||timedStale('soundbites')} onclick={()=>bite(item.id)}>WAV</Button><Button variant="outline" disabled={busy||!available||timedStale('soundbites')} onclick={()=>bite(item.id,true)}>Save to library</Button><label class="flex items-center gap-2 text-sm"><Checkbox bind:checked={item.selected} onCheckedChange={changed}/>Include in package</label></div></div>{/each}{#if pkg.suggestions?.soundbites.length}<ul class="list-disc pl-5 text-sm">{#each pkg.suggestions.soundbites as s}<li>{s.title} · {subtitleTime(s.start)}–{subtitleTime(s.end)}</li>{/each}</ul><Button variant="outline" onclick={()=>accept('soundbites')}>Use suggested soundbites</Button>{/if}
        {/if}
        {#if ['chapters','transcript','soundbites'].includes(section)&&pkg.source&&current}<Button variant="outline" onclick={()=>{pkg.timingFingerprints[section as 'chapters'|'transcript'|'soundbites']=pkg.source!.fingerprint;changed();}}>Confirm timestamps match this mix</Button>{/if}
      </Tabs.Content>{/each}
    </Tabs.Root>
    <p class="text-xs text-text-2">The ZIP includes your finished WAV, title, description, reviewed chapters, transcript (TXT/SRT/VTT), and selected soundbites. Missing optional materials do not block download.</p>
  {/if}
  {#if busy}<div role="status" class="fixed right-4 top-24 z-50 flex max-w-sm items-center gap-3 rounded-xl border border-border bg-surface p-4 shadow-lg"><Spinner label="Preparing files"/>{progress}<Button size="sm" variant="ghost" onclick={()=>controller?.abort()}>Cancel</Button></div>{/if}
</div>
